services:
  nuxt:
    image: mojito-web:dev
    container_name: nuxt
    build:
      context: .
      dockerfile: docker/nuxt/Dockerfile
      target: development
      args:
        - NODE_ENV=development
      cache_from:
        - "mojito-web:dev"
        - "mojito-web:latest"
        - "*"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
    tty: true
    command: yarn dev

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: unless-stopped

  django:
    image: ghcr.io/mojitoteam/api:latest
    container_name: django
    env_file:
      - .env
    command: python -Wd manage.py runserver 0.0.0.0:8000

volumes:
  data:
  node_modules:

networks:
  main:
