services:
  nuxt:
    image: mojito-web:dev
    container_name: nuxt
    tty: true
    hostname: nuxt
    build:
      context: .
      dockerfile: docker/nuxt/Dockerfile
      target: development
      args:
        - NODE_ENV=development
      cache_from:
        - "mojito-web:dev"
        - "mojito-web:latest"
        - "*"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - 3000:3000
      - 24678:24678
    depends_on:
      - django
      - postgres
    command: yarn dev

  postgres:
    image: postgres:15.3-alpine
    container_name: postgres
    hostname: postgres
    volumes:
      - data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - main
    restart: unless-stopped

  django:
    image: ghcr.io/mojitoteam/api:latest
    container_name: django
    tty: true
    hostname: django
    env_file:
      - .env
    networks:
      - main
    ports:
      - 8000:8000
    depends_on:
      - postgres
    command: python -Wd manage.py runserver 0.0.0.0:8000

volumes:
  data:
  node_modules:

networks:
  main:
